# 数组方法

## 求和

In [1]:
%pylab

Using matplotlib backend: <object object at 0x0000024CAC128470>
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
a= array([[1, 2, 3, 4], 
          [5, 6, 7, 9]])
sum(a)

37

In [3]:
sum(a, axis=0)

array([ 6,  8, 10, 13])

In [4]:
sum(a, axis=1)


array([10, 27])

In [5]:
a.sum()

37

In [7]:
a.sum(axis=-1)

array([10, 27])

## 求积

In [8]:
a.prod()

45360

In [9]:
a.prod(axis=0)

array([ 5, 12, 21, 36])