# 数组类型
## 复数

In [1]:
from numpy import *
a = array([1+1j, 2, 3, 4])
a

array([1.+1.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [2]:
a.dtype

dtype('complex128')

In [3]:
a.real

array([1., 2., 3., 4.])

In [4]:
a.imag

array([1., 0., 0., 0.])

In [7]:
a.imag = [2, 3, 4, -5]
a

array([1.+2.j, 2.+3.j, 3.+4.j, 4.-5.j])

In [8]:
a.conj()

array([1.-2.j, 2.-3.j, 3.-4.j, 4.+5.j])

In [9]:
a + a.conj()

array([2.+0.j, 4.+0.j, 6.+0.j, 8.+0.j])